baseURL = 'https://yancolabs.com/'
languageCode = 'en-us'
title = 'Yancolabs'

[languages]
    [languages.en]
        languageName = 'en-us'
        weight = 1
    [languages.ru]
        languageCode = 'ru-ru'
        languageName = 'ru-ru'
        weight = 2

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
